##
## Collision spheres for Boston Dynamics Spot Arm
##
collision_spheres:
    arm0_link_sh0:
        - "center": [-0.022, -0.068, -0.002]
          "radius": 0.0663
        - "center": [-0.01, 0.058, 0.0]
          "radius": 0.0762
    arm0_link_sh1:
        - "center": [0.191, 0.007, 0.0]
          "radius": 0.0622
        - "center": [0.128, -0.001, 0.001]
          "radius": 0.0622
        - "center": [0.249, -0.007, 0.0]
          "radius": 0.0622
        - "center": [0.33, -0.01, 0.0]
          "radius": 0.059
    arm0_link_hr0:
        - "center": [0.17, -0.002, 0.0]
          "radius": 0.06
    arm0_link_el0:
        - "center": [0.059, 0.0, 0.061]
          "radius": 0.0659
        - "center": [0.018, 0.011, 0.018]
          "radius": 0.0549
        - "center": [0.096, -0.003, 0.073]
          "radius": 0.0595
    arm0_link_el1:
        - "center": [-0.218, 0.0, 0.001]
          "radius": 0.0567
        - "center": [-0.141, 0.001, 0.001]
          "radius": 0.0558
        - "center": [-0.085, 0.003, -0.001]
          "radius": 0.0539
        - "center": [0.002, -0.059, -0.018]
          "radius": 0.0291
        - "center": [-0.035, -0.056, 0.021]
          "radius": 0.0291
        - "center": [0.007, -0.058, 0.01]
          "radius": 0.0291
    arm0_link_wr0:
        - "center": [0.002, -0.009, 0.004]
          "radius": 0.0497
        - "center": [0.028, -0.01, 0.007]
          "radius": 0.0497
    arm0_link_wr1:
        - "center": [0.098, -0.009, 0.005]
          "radius": 0.0468
        - "center": [0.1, -0.009, -0.041]
          "radius": 0.039
        - "center": [0.111, 0.017, -0.04]
          "radius": 0.0373
        - "center": [0.112, 0.017, 0.01]
          "radius": 0.0434
        - "center": [0.068, 0.02, 0.012]
          "radius": 0.0322
        - "center": [0.215, -0.001, -0.048]
          "radius": 0.0216
        - "center": [0.183, -0.006, -0.048]
          "radius": 0.0212
        - "center": [0.168, 0.015, -0.047]
          "radius": 0.0212
        - "center": [0.16, -0.017, -0.047]
          "radius": 0.0212
        - "center": [0.157, 0.003, -0.049]
          "radius": 0.0212
        - "center": [0.186, 0.009, -0.047]
          "radius": 0.0212
        - "center": [0.157, 0.026, -0.046]
          "radius": 0.0196
        - "center": [0.174, -0.017, -0.047]
          "radius": 0.0204
        - "center": [0.224, -0.006, -0.035]
          "radius": 0.0217
    arm0_link_fngr:
        - "center": [0.003, -0.044, 0.0]
          "radius": 0.0245
        - "center": [0.079, -0.023, -0.025]
          "radius": 0.0234
        - "center": [0.084, 0.02, -0.026]
          "radius": 0.0226
        - "center": [0.069, 0.029, -0.02]
          "radius": 0.0219
        - "center": [0.106, -0.015, -0.036]
          "radius": 0.0204
        - "center": [0.065, -0.029, -0.012]
          "radius": 0.0204
        - "center": [0.109, 0.01, -0.037]
          "radius": 0.0197
        - "center": [0.09, -0.014, -0.03]
          "radius": 0.0212
        - "center": [0.061, 0.034, -0.016]
          "radius": 0.0204
        - "center": [0.091, 0.018, -0.029]
          "radius": 0.0219
        - "center": [0.088, 0.006, -0.032]
          "radius": 0.019
        - "center": [0.091, -0.022, -0.031]
          "radius": 0.0212
        - "center": [0.109, 0.019, -0.041]
          "radius": 0.0183
        - "center": [0.058, 0.03, -0.008]
          "radius": 0.0183
